// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsmwkunyjkfjflrdtlpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbXdrdW55amtmamZscmR0bHBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NjIwNjMsImV4cCI6MjA1NzUzODA2M30.LNntBeRn0tRRKo5QB2ZcF2ecuaeA3zfAU8R7JgrcDsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);